# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69bdc39e096cc97852cf451eeff9d19544e0e61e068e28e6f6380072b25bfa2a910b08d0442eb634e4866b01f6b769fae29afb1207c771f2ab0da29065cb4977

test:
  secret_key_base: 8343a1536c2f9c013a31fe0a826a16cae995d0e8868a1996fd85b606bf17296969b48db37c97ed5ce67f265b1a4a8235d0407a43fb16f57cde8c0ebd09d73b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
